language: node_js
sudo: false
env:
  matrix:
  - CI=true
  global:
    secure: UwxWPl/vl9gTYvh1o33lfit9jJOllmyxfLLKXQa2QW9xpfoYKLWi0IEtfdyOFlbBnFJ60NvGZ+ma1WDjYNaHca8hrlRjuaRlW6lkPxypTXLP/q+1ZEs69HOgBdr8jLtedTe/vhOW6s5k4vzamPWOxeuydOyLeXM/wYBloAW/nkQ=
node_js:
- '0.12'
before_script:
- "./bin/run-jscs.sh"
after_script:
- npm run coveralls
notifications:
  email:
  - ogataken@gmail.com
branches:
  only:
  - master
  - /^ping\/.*$/
